# Generated by Django 4.2.6 on 2023-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwith_pdf', '0002_remove_pdf_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
