# Generated by Django 4.2.6 on 2023-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwith_pdf', '0003_alter_pdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
