# Generated by Django 4.2.6 on 2023-10-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatwith_pdf', '0004_alter_pdf_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.TextField(default='No answer'),
        ),
        migrations.AddField(
            model_name='message',
            name='pdf_files',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chatwith_pdf.pdf'),
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.TextField(default='No question'),
        ),
    ]
